### PR TITLE
added supply for KOIN coin

### PR DESCRIPTION
**Pull request by aseandude**

### CODE REVIEW

**Comment by pbca26** [comment]
do you run your own seed nodes?

**Comment by aseandude** [comment]
I'm looking for Dev team    they are back in 20 min or so

Regards

**Comment by aseandude** [comment]
Yes. it is at 3.0.32.10

**Comment by pbca26** [comment]
you need to add "addnode" param then
here is an example https://github.com/KomodoPlatform/Agama/blob/dev/routes/chainParams.js#L56

**Comment by aseandude** [comment]
what is status please for Agama wallet add for KOIN and for add KOIN to 
BarterDEX?

Regards

**Pull request merged**
