### PR TITLE
Allocate empty object when doing Ethereum/ERC20 login

### PR DESCRIPTION
**Pull request by Lucioric2000**
When adding an ethereum coin, 0 balance is shown in a wallet, and an error message is shown in the console. The error message is that is tried to add a property to api.eth.connect when it contains a null value. For avoiding this situation, api.eth.connect must be assigned to an empty object when starting to work with a Ethereum wallet, this is, at login.
I also deleted the Agama installer file that is for my local fork, and created a small Python script that generates the development version string. But then is is needed to have Python installed in the system that does the install. If someone can convert the Python script (buildscripts/devversion.py) to a shell one...

### CODE REVIEW

**Comment by Lucioric2000** [comment]
This pull request was not about exposing the token, was about correcting a bug in the Eth/erc20 coins affter logging out and logging in again.

**Comment by Lucioric2000** [comment]
I removed the files that exposed the token.

**Comment by Lucioric2000** [comment]
The change that I wanted to do as a collaboration to the software is adding the line:
api.eth.connect = {};
after line 13 of routes/api/eth/auth.js

**Comment by pbca26** [comment]
thanks i added this change after you pointed out this bit
i will try to review the pr soon

**Pull request merged**
